### PR TITLE
upgrade elm to 0.17

### PR DESCRIPTION
**Pull request by WangBoxue**

### CODE REVIEW

**Comment by simonh1000** [comment]
This looks good. Let me check it out in detail and get back to you

**Comment by simonh1000** [comment]
Just to let you know that I have not forgotten about this. I've needed to do file uploads again and have started playing around with the library with this new use case. That's lead to some changes. I also need to update all of the examples in the library documentation

**Comment by WangBoxue** [comment]
It's OK. Take your time.

**Comment by danyx23** [comment]
I have had a look at this and it seems reasonable. Simon, should we go ahead and merge this? What are your other changes that you mentioned in the comment above?

**Comment by danyx23** [comment]
One interface change I am not so sure about is to make readAsTextFile return a tuple of strings where the first is the file modification date. I think that should be done differently, probably as a separate function?

**Comment by simonh1000** [comment]
The key issue is how we deal with the native code. I found in a new project I'm working on that I did not need filereader as such, as the blobs resulting from dragNdrop and from the file input contained the files, and could be passed via a port to be used with e.g. the Amazon S3 SDK. I'm wondering whether the native code should be moved to a blog post so that the rest can be published explicitly?

**Pull request merged**
