### PR TITLE
Relaxed elm-mimetype upper bound

### PR DESCRIPTION
**Pull request by aleator**

### CODE REVIEW

**Comment by aleator** [comment]
Oops. Messed the branch. Sorry.

**Comment by simonh1000** [comment]
Could you open an issue first so I know what your challenges are?  And note that native code is not possible at all in 0.19 so this repo will be modified considerably to work with ports

**Comment by aleator** [comment]
Sorry about this. I was about to re-open this when I get the git untangled. 

The whole issue was that I needed 4.0.0 version of MimeType. If the whole code is going to be overhauled in the near future, I can live with a fork until things settle down.

**Comment by simonh1000** [comment]
ah, I would not expect to have any worries about a PR to update mime type

**Comment by aleator** [comment]
Ok. Cool. I removed an unnecessary commit (the native package marker) and things should work now.

**Comment by simonh1000** [comment]
Thanks - I needed to tweak the commit a bit t make it in line with standard Elm practise

**Comment by aleator** [comment]
Thank you! I'm not an elm guy, but I should've checked the version policy beforehand.

**Pull request merged**
